#ifndef TESTS_INC
#define TESTS_INC

#include "Instances/KeyConverted.h"
#include "Instances/KeyConvertedCustom.h"
#include "Instances/KeyLimitedRange.h"
#include "Instances/KeyLimitedRangeSimple.h"
#include "Instances/QKeyList.h"
#include "Instances/QKeyVector.h"
#include "Instances/QKeyMap.h"
#include "Instances/StdKeyList.h"
#include "Instances/StdKeyMap.h"
#include "Instances/StdKeyUnorderedMap.h"
#include "Instances/StdKeyVector.h"
#include "Instances/QInput.h"

#endif // TESTS_INC

