#ifndef OPENGLFUNCTIONS_3_3_CORE_H
#define OPENGLFUNCTIONS_3_3_CORE_H

#include <OpenGLCommon>
#include <QOpenGLFunctions_3_3_Core>

#if !defined(QT_NO_OPENGL) && !defined(QT_OPENGL_ES_2)

class OpenGLFunctions_3_3_Core : public QOpenGLFunctions_3_3_Core
{
public:
  inline OpenGLFunctions_3_3_Core() : QOpenGLFunctions_3_3_Core() {}
  inline ~OpenGLFunctions_3_3_Core() {}

  GL_PROFILE(glViewport, GLint, GLint, GLsizei, GLsizei);
  GL_PROFILE(glDepthRange, GLdouble, GLdouble);
  GL_PROFILE(glIsEnabled, GLenum);
  GL_PROFILE(glGetTexLevelParameteriv, GLenum, GLint, GLenum, GLint *);
  GL_PROFILE(glGetTexLevelParameterfv, GLenum, GLint, GLenum, GLfloat *);
  GL_PROFILE(glGetTexParameteriv, GLenum, GLenum, GLint *);
  GL_PROFILE(glGetTexParameterfv, GLenum, GLenum, GLfloat *);
  GL_PROFILE(glGetTexImage, GLenum, GLint, GLenum, GLenum, GLvoid *);
  GL_PROFILE(glGetString, GLenum);
  GL_PROFILE(glGetIntegerv, GLenum, GLint *);
  GL_PROFILE(glGetFloatv, GLenum, GLfloat *);
  GL_PROFILE(glGetError, );
  GL_PROFILE(glGetDoublev, GLenum, GLdouble *);
  GL_PROFILE(glGetBooleanv, GLenum, GLboolean *);
  GL_PROFILE(glReadPixels, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid *);
  GL_PROFILE(glReadBuffer, GLenum);
  GL_PROFILE(glPixelStorei, GLenum, GLint);
  GL_PROFILE(glPixelStoref, GLenum, GLfloat);
  GL_PROFILE(glDepthFunc, GLenum);
  GL_PROFILE(glStencilOp, GLenum, GLenum, GLenum);
  GL_PROFILE(glStencilFunc, GLenum, GLint, GLuint);
  GL_PROFILE(glLogicOp, GLenum opcode);
  GL_PROFILE(glBlendFunc, GLenum sfactor, GLenum);
  GL_PROFILE(glFlush, );
  GL_PROFILE(glFinish, );
  GL_PROFILE(glEnable, GLenum);
  GL_PROFILE(glDisable, GLenum);
  GL_PROFILE(glDepthMask, GLboolean);
  GL_PROFILE(glColorMask, GLboolean, GLboolean, GLboolean, GLboolean);
  GL_PROFILE(glStencilMask, GLuint);
  GL_PROFILE(glClearDepth, GLdouble);
  GL_PROFILE(glClearStencil, GLint);
  GL_PROFILE(glClearColor, GLfloat, GLfloat, GLfloat, GLfloat);
  GL_PROFILE(glClear, GLbitfield);
  GL_PROFILE(glDrawBuffer, GLenum);
  GL_PROFILE(glTexImage2D, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glTexImage1D, GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glTexParameteriv, GLenum, GLenum, const GLint *);
  GL_PROFILE(glTexParameteri, GLenum, GLenum, GLint);
  GL_PROFILE(glTexParameterfv, GLenum, GLenum, const GLfloat *);
  GL_PROFILE(glTexParameterf, GLenum, GLenum, GLfloat);
  GL_PROFILE(glScissor, GLint, GLint, GLsizei, GLsizei);
  GL_PROFILE(glPolygonMode, GLenum, GLenum);
  GL_PROFILE(glPointSize, GLfloat);
  GL_PROFILE(glLineWidth, GLfloat);
  GL_PROFILE(glHint, GLenum, GLenum);
  GL_PROFILE(glFrontFace, GLenum);
  GL_PROFILE(glCullFace, GLenum);
  GL_PROFILE(glIndexubv, const GLubyte *);
  GL_PROFILE(glIndexub, GLubyte);
  GL_PROFILE(glIsTexture, GLuint);
  GL_PROFILE(glGenTextures, GLsizei, GLuint *);
  GL_PROFILE(glDeleteTextures, GLsizei, const GLuint *);
  GL_PROFILE(glBindTexture, GLenum, GLuint);
  GL_PROFILE(glTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glTexSubImage1D, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glCopyTexSubImage2D, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
  GL_PROFILE(glCopyTexSubImage1D, GLenum, GLint, GLint, GLint, GLint, GLsizei);
  GL_PROFILE(glCopyTexImage2D, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint);
  GL_PROFILE(glCopyTexImage1D, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint);
  GL_PROFILE(glPolygonOffset, GLfloat, GLfloat);
  GL_PROFILE(glGetPointerv, GLenum, GLvoid* *);
  GL_PROFILE(glDrawElements, GLenum, GLsizei, GLenum, const GLvoid *);
  GL_PROFILE(glDrawArrays, GLenum, GLint, GLsizei);
  GL_PROFILE(glCopyTexSubImage3D, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei);
  GL_PROFILE(glTexSubImage3D, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glTexImage3D, GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
  GL_PROFILE(glDrawRangeElements, GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
  GL_PROFILE(glBlendEquation, GLenum);
  GL_PROFILE(glBlendColor, GLfloat, GLfloat, GLfloat, GLfloat);
  GL_PROFILE(glGetCompressedTexImage, GLenum, GLint, GLvoid *);
  GL_PROFILE(glCompressedTexSubImage1D, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
  GL_PROFILE(glCompressedTexSubImage2D, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
  GL_PROFILE(glCompressedTexSubImage3D, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
  GL_PROFILE(glCompressedTexImage1D, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
  GL_PROFILE(glCompressedTexImage2D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
  GL_PROFILE(glCompressedTexImage3D, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
  GL_PROFILE(glSampleCoverage, GLfloat, GLboolean);
  GL_PROFILE(glActiveTexture, GLenum);
  GL_PROFILE(glPointParameteriv, GLenum, const GLint *);
  GL_PROFILE(glPointParameteri, GLenum, GLint);
  GL_PROFILE(glPointParameterfv, GLenum, const GLfloat *);
  GL_PROFILE(glPointParameterf, GLenum, GLfloat);
  GL_PROFILE(glMultiDrawElements, GLenum, const GLsizei *, GLenum, const GLvoid* const *, GLsizei);
  GL_PROFILE(glMultiDrawArrays, GLenum, const GLint *, const GLsizei *, GLsizei);
  GL_PROFILE(glBlendFuncSeparate, GLenum, GLenum, GLenum, GLenum);
  GL_PROFILE(glGetBufferPointerv, GLenum, GLenum, GLvoid* *);
  GL_PROFILE(glGetBufferParameteriv, GLenum, GLenum, GLint *);
  GL_PROFILE(glUnmapBuffer, GLenum);
  GL_PROFILE(glMapBuffer, GLenum, GLenum);
  GL_PROFILE(glGetBufferSubData, GLenum, GLintptr, GLsizeiptr, GLvoid *);
  GL_PROFILE(glBufferSubData, GLenum, GLintptr, GLsizeiptr, const GLvoid *);
  GL_PROFILE(glBufferData, GLenum, GLsizeiptr, const GLvoid *, GLenum);
  GL_PROFILE(glIsBuffer, GLuint);
  GL_PROFILE(glGenBuffers, GLsizei, GLuint *);
  GL_PROFILE(glDeleteBuffers, GLsizei, const GLuint *);
  GL_PROFILE(glBindBuffer, GLenum, GLuint);
  GL_PROFILE(glGetQueryObjectuiv, GLuint, GLenum, GLuint *);
  GL_PROFILE(glGetQueryObjectiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glGetQueryiv, GLenum, GLenum, GLint *);
  GL_PROFILE(glEndQuery, GLenum);
  GL_PROFILE(glBeginQuery, GLenum, GLuint);
  GL_PROFILE(glIsQuery, GLuint);
  GL_PROFILE(glDeleteQueries, GLsizei, const GLuint *);
  GL_PROFILE(glGenQueries, GLsizei, GLuint *);
  GL_PROFILE(glVertexAttribPointer, GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *);
  GL_PROFILE(glValidateProgram, GLuint);
  GL_PROFILE(glUniformMatrix4fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix3fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix2fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniform4iv, GLint, GLsizei, const GLint *);
  GL_PROFILE(glUniform3iv, GLint, GLsizei, const GLint *);
  GL_PROFILE(glUniform2iv, GLint, GLsizei, const GLint *);
  GL_PROFILE(glUniform1iv, GLint, GLsizei, const GLint *);
  GL_PROFILE(glUniform4fv, GLint, GLsizei, const GLfloat *);
  GL_PROFILE(glUniform3fv, GLint, GLsizei, const GLfloat *);
  GL_PROFILE(glUniform2fv, GLint, GLsizei, const GLfloat *);
  GL_PROFILE(glUniform1fv, GLint, GLsizei, const GLfloat *);
  GL_PROFILE(glUniform4i, GLint, GLint, GLint, GLint, GLint);
  GL_PROFILE(glUniform3i, GLint, GLint, GLint, GLint);
  GL_PROFILE(glUniform2i, GLint, GLint, GLint);
  GL_PROFILE(glUniform1i, GLint, GLint);
  GL_PROFILE(glUniform4f, GLint, GLfloat, GLfloat, GLfloat, GLfloat);
  GL_PROFILE(glUniform3f, GLint, GLfloat, GLfloat, GLfloat);
  GL_PROFILE(glUniform2f, GLint, GLfloat, GLfloat);
  GL_PROFILE(glUniform1f, GLint, GLfloat);
  GL_PROFILE(glUseProgram, GLuint);
  GL_PROFILE(glShaderSource, GLuint, GLsizei, const GLchar* const *, const GLint *);
  GL_PROFILE(glLinkProgram, GLuint);
  GL_PROFILE(glIsShader, GLuint);
  GL_PROFILE(glIsProgram, GLuint);
  GL_PROFILE(glGetVertexAttribPointerv, GLuint, GLenum, GLvoid* *);
  GL_PROFILE(glGetVertexAttribiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glGetVertexAttribfv, GLuint, GLenum, GLfloat *);
  GL_PROFILE(glGetVertexAttribdv, GLuint, GLenum, GLdouble *);
  GL_PROFILE(glGetUniformiv, GLuint, GLint, GLint *);
  GL_PROFILE(glGetUniformfv, GLuint, GLint, GLfloat *);
  GL_PROFILE(glGetUniformLocation, GLuint, const GLchar *);
  GL_PROFILE(glGetShaderSource, GLuint, GLsizei bufSize, GLsizei *, GLchar *source);
  GL_PROFILE(glGetShaderInfoLog, GLuint, GLsizei bufSize, GLsizei *, GLchar *infoLog);
  GL_PROFILE(glGetShaderiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glGetProgramInfoLog, GLuint, GLsizei bufSize, GLsizei *, GLchar *infoLog);
  GL_PROFILE(glGetProgramiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glGetAttribLocation, GLuint, const GLchar *);
  GL_PROFILE(glGetAttachedShaders, GLuint, GLsizei maxCount, GLsizei *, GLuint *obj);
  GL_PROFILE(glGetActiveUniform, GLuint, GLuint, GLsizei bufSize, GLsizei *, GLint *size, GLenum *type, GLchar *);
  GL_PROFILE(glGetActiveAttrib, GLuint, GLuint, GLsizei bufSize, GLsizei *, GLint *size, GLenum *type, GLchar *);
  GL_PROFILE(glEnableVertexAttribArray, GLuint);
  GL_PROFILE(glDisableVertexAttribArray, GLuint);
  GL_PROFILE(glDetachShader, GLuint, GLuint);
  GL_PROFILE(glDeleteShader, GLuint);
  GL_PROFILE(glDeleteProgram, GLuint);
  GL_PROFILE(glCreateShader, GLenum);
  GL_PROFILE(glCreateProgram, );
  GL_PROFILE(glCompileShader, GLuint);
  GL_PROFILE(glBindAttribLocation, GLuint, GLuint, const GLchar *);
  GL_PROFILE(glAttachShader, GLuint, GLuint);
  GL_PROFILE(glStencilMaskSeparate, GLenum, GLuint);
  GL_PROFILE(glStencilFuncSeparate, GLenum, GLenum, GLint, GLuint);
  GL_PROFILE(glStencilOpSeparate, GLenum, GLenum, GLenum, GLenum);
  GL_PROFILE(glDrawBuffers, GLsizei, const GLenum *);
  GL_PROFILE(glBlendEquationSeparate, GLenum, GLenum);
  GL_PROFILE(glUniformMatrix4x3fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix3x4fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix4x2fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix2x4fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix3x2fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glUniformMatrix2x3fv, GLint, GLsizei, GLboolean, const GLfloat *);
  GL_PROFILE(glIsVertexArray, GLuint);
  GL_PROFILE(glGenVertexArrays, GLsizei, GLuint *);
  GL_PROFILE(glDeleteVertexArrays, GLsizei, const GLuint *);
  GL_PROFILE(glBindVertexArray, GLuint);
  GL_PROFILE(glFlushMappedBufferRange, GLenum, GLintptr, GLsizeiptr);
  GL_PROFILE(glMapBufferRange, GLenum, GLintptr, GLsizeiptr, GLbitfield);
  GL_PROFILE(glFramebufferTextureLayer, GLenum, GLenum, GLuint, GLint, GLint layer);
  GL_PROFILE(glRenderbufferStorageMultisample, GLenum, GLsizei, GLenum, GLsizei, GLsizei);
  GL_PROFILE(glBlitFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint, GLint, GLbitfield, GLenum filter);
  GL_PROFILE(glGenerateMipmap, GLenum);
  GL_PROFILE(glGetFramebufferAttachmentParameteriv, GLenum, GLenum, GLenum, GLint *);
  GL_PROFILE(glFramebufferRenderbuffer, GLenum, GLenum, GLenum renderbuffertarget, GLuint renderbuffer);
  GL_PROFILE(glFramebufferTexture3D, GLenum, GLenum, GLenum, GLuint, GLint, GLint);
  GL_PROFILE(glFramebufferTexture2D, GLenum, GLenum, GLenum, GLuint, GLint);
  GL_PROFILE(glFramebufferTexture1D, GLenum, GLenum, GLenum, GLuint, GLint);
  GL_PROFILE(glCheckFramebufferStatus, GLenum);
  GL_PROFILE(glGenFramebuffers, GLsizei, GLuint *framebuffers);
  GL_PROFILE(glDeleteFramebuffers, GLsizei, const GLuint *framebuffers);
  GL_PROFILE(glBindFramebuffer, GLenum, GLuint framebuffer);
  GL_PROFILE(glIsFramebuffer, GLuint framebuffer);
  GL_PROFILE(glGetRenderbufferParameteriv, GLenum, GLenum, GLint *);
  GL_PROFILE(glRenderbufferStorage, GLenum, GLenum, GLsizei, GLsizei);
  GL_PROFILE(glGenRenderbuffers, GLsizei, GLuint *renderbuffers);
  GL_PROFILE(glDeleteRenderbuffers, GLsizei, const GLuint *renderbuffers);
  GL_PROFILE(glBindRenderbuffer, GLenum, GLuint renderbuffer);
  GL_PROFILE(glIsRenderbuffer, GLuint renderbuffer);
  GL_PROFILE(glGetStringi, GLenum, GLuint);
  GL_PROFILE(glClearBufferfi, GLenum, GLint, GLfloat, GLint);
  GL_PROFILE(glClearBufferfv, GLenum, GLint, const GLfloat *);
  GL_PROFILE(glClearBufferuiv, GLenum, GLint, const GLuint *);
  GL_PROFILE(glClearBufferiv, GLenum, GLint, const GLint *);
  GL_PROFILE(glGetTexParameterIuiv, GLenum, GLenum, GLuint *);
  GL_PROFILE(glGetTexParameterIiv, GLenum, GLenum, GLint *);
  GL_PROFILE(glTexParameterIuiv, GLenum, GLenum, const GLuint *);
  GL_PROFILE(glTexParameterIiv, GLenum, GLenum, const GLint *);
  GL_PROFILE(glUniform4uiv, GLint, GLsizei, const GLuint *);
  GL_PROFILE(glUniform3uiv, GLint, GLsizei, const GLuint *);
  GL_PROFILE(glUniform2uiv, GLint, GLsizei, const GLuint *);
  GL_PROFILE(glUniform1uiv, GLint, GLsizei, const GLuint *);
  GL_PROFILE(glUniform4ui, GLint, GLuint, GLuint, GLuint, GLuint);
  GL_PROFILE(glUniform3ui, GLint, GLuint, GLuint, GLuint);
  GL_PROFILE(glUniform2ui, GLint, GLuint, GLuint);
  GL_PROFILE(glUniform1ui, GLint, GLuint);
  GL_PROFILE(glGetFragDataLocation, GLuint, const GLchar *);
  GL_PROFILE(glBindFragDataLocation, GLuint, GLuint, const GLchar *);
  GL_PROFILE(glGetUniformuiv, GLuint, GLint, GLuint *);
  GL_PROFILE(glGetVertexAttribIuiv, GLuint, GLenum, GLuint *);
  GL_PROFILE(glGetVertexAttribIiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glVertexAttribIPointer, GLuint, GLint, GLenum, GLsizei, const GLvoid *);
  GL_PROFILE(glEndConditionalRender, );
  GL_PROFILE(glBeginConditionalRender, GLuint, GLenum);
  GL_PROFILE(glClampColor, GLenum, GLenum clamp);
  GL_PROFILE(glGetTransformFeedbackVarying, GLuint, GLuint, GLsizei bufSize, GLsizei *, GLsizei *size, GLenum *type, GLchar *);
  GL_PROFILE(glTransformFeedbackVaryings, GLuint, GLsizei, const GLchar* const *, GLenum);
  GL_PROFILE(glBindBufferBase, GLenum, GLuint, GLuint);
  GL_PROFILE(glBindBufferRange, GLenum, GLuint, GLuint, GLintptr, GLsizeiptr);
  GL_PROFILE(glEndTransformFeedback, );
  GL_PROFILE(glBeginTransformFeedback, GLenum primitiveMode);
  GL_PROFILE(glIsEnabledi, GLenum, GLuint);
  GL_PROFILE(glDisablei, GLenum, GLuint);
  GL_PROFILE(glEnablei, GLenum, GLuint);
  GL_PROFILE(glGetIntegeri_v, GLenum, GLuint, GLint *);
  GL_PROFILE(glGetBooleani_v, GLenum, GLuint, GLboolean *);
  GL_PROFILE(glColorMaski, GLuint, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
  GL_PROFILE(glCopyBufferSubData, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr);
  GL_PROFILE(glUniformBlockBinding, GLuint, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
  GL_PROFILE(glGetActiveUniformBlockName, GLuint, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *, GLchar *uniformBlockName);
  GL_PROFILE(glGetActiveUniformBlockiv, GLuint, GLuint uniformBlockIndex, GLenum, GLint *);
  GL_PROFILE(glGetUniformBlockIndex, GLuint, const GLchar *uniformBlockName);
  GL_PROFILE(glGetActiveUniformName, GLuint, GLuint uniformIndex, GLsizei bufSize, GLsizei *, GLchar *uniformName);
  GL_PROFILE(glGetActiveUniformsiv, GLuint, GLsizei uniformCount, const GLuint *uniformIndices, GLenum, GLint *);
  GL_PROFILE(glGetUniformIndices, GLuint, GLsizei uniformCount, const GLchar* const *uniformNames, GLuint *uniformIndices);
  GL_PROFILE(glPrimitiveRestartIndex, GLuint);
  GL_PROFILE(glTexBuffer, GLenum, GLenum, GLuint);
  GL_PROFILE(glDrawElementsInstanced, GLenum, GLsizei, GLenum, const GLvoid *, GLsizei);
  GL_PROFILE(glDrawArraysInstanced, GLenum, GLint, GLsizei, GLsizei);
  GL_PROFILE(glSampleMaski, GLuint, GLbitfield);
  GL_PROFILE(glGetMultisamplefv, GLenum, GLuint, GLfloat *);
  GL_PROFILE(glTexImage3DMultisample, GLenum, GLsizei, GLint, GLsizei, GLsizei, GLsizei, GLboolean);
  GL_PROFILE(glTexImage2DMultisample, GLenum, GLsizei, GLint, GLsizei, GLsizei, GLboolean);
  GL_PROFILE(glGetSynciv, GLsync, GLenum, GLsizei bufSize, GLsizei *, GLint *);
  GL_PROFILE(glGetInteger64v, GLenum, GLint64 *);
  GL_PROFILE(glWaitSync, GLsync, GLbitfield, GLuint64);
  GL_PROFILE(glClientWaitSync, GLsync, GLbitfield, GLuint64);
  GL_PROFILE(glDeleteSync, GLsync);
  GL_PROFILE(glIsSync, GLsync);
  GL_PROFILE(glFenceSync, GLenum, GLbitfield);
  GL_PROFILE(glProvokingVertex, GLenum);
  GL_PROFILE(glMultiDrawElementsBaseVertex, GLenum, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, const GLint *);
  GL_PROFILE(glDrawElementsInstancedBaseVertex, GLenum, GLsizei, GLenum, const GLvoid *, GLsizei, GLint);
  GL_PROFILE(glDrawRangeElementsBaseVertex, GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *, GLint);
  GL_PROFILE(glDrawElementsBaseVertex, GLenum, GLsizei, GLenum, const GLvoid *, GLint);
  GL_PROFILE(glFramebufferTexture, GLenum, GLenum, GLuint, GLint);
  GL_PROFILE(glGetBufferParameteri64v, GLenum, GLenum, GLint64 *);
  GL_PROFILE(glGetInteger64i_v, GLenum, GLuint, GLint64 *);
  GL_PROFILE(glVertexAttribP4uiv, GLuint, GLenum, GLboolean, const GLuint *);
  GL_PROFILE(glVertexAttribP4ui, GLuint, GLenum, GLboolean, GLuint);
  GL_PROFILE(glVertexAttribP3uiv, GLuint, GLenum, GLboolean, const GLuint *);
  GL_PROFILE(glVertexAttribP3ui, GLuint, GLenum, GLboolean, GLuint);
  GL_PROFILE(glVertexAttribP2uiv, GLuint, GLenum, GLboolean, const GLuint *);
  GL_PROFILE(glVertexAttribP2ui, GLuint, GLenum, GLboolean, GLuint);
  GL_PROFILE(glVertexAttribP1uiv, GLuint, GLenum, GLboolean, const GLuint *);
  GL_PROFILE(glVertexAttribP1ui, GLuint, GLenum, GLboolean, GLuint);
  GL_PROFILE(glSecondaryColorP3uiv, GLenum, const GLuint *);
  GL_PROFILE(glSecondaryColorP3ui, GLenum, GLuint);
  GL_PROFILE(glColorP4uiv, GLenum, const GLuint *);
  GL_PROFILE(glColorP4ui, GLenum, GLuint);
  GL_PROFILE(glColorP3uiv, GLenum, const GLuint *);
  GL_PROFILE(glColorP3ui, GLenum, GLuint);
  GL_PROFILE(glNormalP3uiv, GLenum, const GLuint *);
  GL_PROFILE(glNormalP3ui, GLenum, GLuint);
  GL_PROFILE(glMultiTexCoordP4uiv, GLenum, GLenum, const GLuint *);
  GL_PROFILE(glMultiTexCoordP4ui, GLenum, GLenum, GLuint);
  GL_PROFILE(glMultiTexCoordP3uiv, GLenum, GLenum, const GLuint *);
  GL_PROFILE(glMultiTexCoordP3ui, GLenum, GLenum, GLuint);
  GL_PROFILE(glMultiTexCoordP2uiv, GLenum, GLenum, const GLuint *);
  GL_PROFILE(glMultiTexCoordP2ui, GLenum, GLenum, GLuint);
  GL_PROFILE(glMultiTexCoordP1uiv, GLenum, GLenum, const GLuint *);
  GL_PROFILE(glMultiTexCoordP1ui, GLenum, GLenum, GLuint);
  GL_PROFILE(glTexCoordP4uiv, GLenum, const GLuint *);
  GL_PROFILE(glTexCoordP4ui, GLenum, GLuint);
  GL_PROFILE(glTexCoordP3uiv, GLenum, const GLuint *);
  GL_PROFILE(glTexCoordP3ui, GLenum, GLuint);
  GL_PROFILE(glTexCoordP2uiv, GLenum, const GLuint *);
  GL_PROFILE(glTexCoordP2ui, GLenum, GLuint);
  GL_PROFILE(glTexCoordP1uiv, GLenum, const GLuint *);
  GL_PROFILE(glTexCoordP1ui, GLenum, GLuint);
  GL_PROFILE(glVertexP4uiv, GLenum, const GLuint *);
  GL_PROFILE(glVertexP4ui, GLenum, GLuint);
  GL_PROFILE(glVertexP3uiv, GLenum, const GLuint *);
  GL_PROFILE(glVertexP3ui, GLenum, GLuint);
  GL_PROFILE(glVertexP2uiv, GLenum, const GLuint *);
  GL_PROFILE(glVertexP2ui, GLenum, GLuint);
  GL_PROFILE(glGetQueryObjectui64v, GLuint, GLenum, GLuint64 *);
  GL_PROFILE(glGetQueryObjecti64v, GLuint, GLenum, GLint64 *);
  GL_PROFILE(glQueryCounter, GLuint, GLenum);
  GL_PROFILE(glGetSamplerParameterIuiv, GLuint, GLenum, GLuint *);
  GL_PROFILE(glGetSamplerParameterfv, GLuint, GLenum, GLfloat *);
  GL_PROFILE(glGetSamplerParameterIiv, GLuint, GLenum, GLint *);
  GL_PROFILE(glGetSamplerParameteriv, GLuint, GLenum, GLint *);
  GL_PROFILE(glSamplerParameterIuiv, GLuint, GLenum, const GLuint *);
  GL_PROFILE(glSamplerParameterIiv, GLuint, GLenum, const GLint *);
  GL_PROFILE(glSamplerParameterfv, GLuint, GLenum, const GLfloat *);
  GL_PROFILE(glSamplerParameterf, GLuint, GLenum, GLfloat);
  GL_PROFILE(glSamplerParameteriv, GLuint, GLenum, const GLint *);
  GL_PROFILE(glSamplerParameteri, GLuint, GLenum, GLint);
  GL_PROFILE(glBindSampler, GLuint, GLuint);
  GL_PROFILE(glIsSampler, GLuint);
  GL_PROFILE(glDeleteSamplers, GLsizei, const GLuint *);
  GL_PROFILE(glGenSamplers, GLsizei, GLuint *);
  GL_PROFILE(glGetFragDataIndex, GLuint, const GLchar *);
  GL_PROFILE(glBindFragDataLocationIndexed, GLuint, GLuint, GLuint, const GLchar *);
  GL_PROFILE(glVertexAttribDivisor, GLuint, GLuint);


};

#endif // !QT_NO_OPENGL && !QT_OPENGL_ES_2

#endif // OPENGLFUNCTIONS_3_3_CORE_H

